name: Lives
version: '${project.version}'
main: me.sentientp.lives.Lives
api-version: 1.17
authors: [ SentientPlatypus ]
description: Life system for SMP. includes life donation and lifestealing.
commands:
  stats:
    description: See your stats!
  donate:
    description: donate a life!
  getlives:
    description: add lives to a person