name: Lives
version: '1.0-SNAPSHOT'
main: me.sentientp.lives.Lives
api-version: 1.17
authors: [ SentientPlatypus ]
description: Life system for SMP. includes life donation and lifestealing.
commands:
  stats:
    description: See your stats!
    usage: /stats
  donate:
    description: donate a life!
    usage: /donate
  getlives:
    description: add lives to a person
    usage: /getlives <int> <player>
  reset:
    description: resets a players life data to default
    usage: /reset <player>